# Generated by Django 4.2.1 on 2023-06-13 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_orderitems_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='order_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Out for Shipping', 'Out for Shipping'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
