# Generated by Django 4.2.1 on 2023-06-28 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0009_orderitems_product_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitems',
            name='product',
        ),
        migrations.RemoveField(
            model_name='orderitems',
            name='product_size',
        ),
    ]
