# Generated by Django 4.2.1 on 2023-06-30 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0012_order_delivery_date_alter_order_delivery_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='delivery_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
