# Generated by Django 4.2.1 on 2023-06-30 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0014_alter_order_delivery_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='return_problem',
            field=models.TextField(blank=True, null=True),
        ),
    ]
