# Generated by Django 4.2.1 on 2023-05-20 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_category_product_productsize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=10000, verbose_name='description'),
        ),
    ]
