# Generated by Django 4.2.1 on 2023-05-20 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsize',
            name='product_photo',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
