# Generated by Django 4.2.1 on 2023-06-09 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_profilephoto_profileaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileaddress',
            name='house_name',
            field=models.CharField(default=1, max_length=100, verbose_name='name'),
            preserve_default=False,
        ),
    ]
