# Generated by Django 4.2.1 on 2023-06-13 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='product_size',
        ),
    ]
