# Generated by Django 4.2.1 on 2023-06-28 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_remove_coupon_coupon_pic_coupon_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='discount_type',
            field=models.CharField(choices=[('Amount', 'Amount'), ('Percentage', 'Percentage')], max_length=20),
        ),
    ]
